name: hashroute
description: >
    hashroute.dart is a simple location hash router for Dart.
dependencies:
    browser: any
version: 2.0.1
author: Andreas Krennmair <ak@synflood.at>
homepage: https://github.com/akrennmair/hashroute.dart
